# Navigation Links
# The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Technical Notes
    url: docs/
    weight: 20
  - name: Video Lectures
    url: /videos/
    weight: 30
    
# Sidebar for the documentation pages
sidebar:
  - identifier: ""
    name: ""
    params:
      type: ""
    weight: ""
  - identifier: ""
    name: ""
    url: ""
    weight: ""
  - identifier: ""
    name: ""
    url: ""
    weight: ""
